// Generated by gencpp from file propio/AttachDetach.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_ATTACHDETACH_H
#define PROPIO_MESSAGE_ATTACHDETACH_H

#include <ros/service_traits.h>


#include <propio/AttachDetachRequest.h>
#include <propio/AttachDetachResponse.h>


namespace propio
{

struct AttachDetach
{

typedef AttachDetachRequest Request;
typedef AttachDetachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttachDetach
} // namespace propio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::propio::AttachDetach > {
  static const char* value()
  {
    return "1e9f418fc6a1ffcaf360d719404f78ea";
  }

  static const char* value(const ::propio::AttachDetach&) { return value(); }
};

template<>
struct DataType< ::propio::AttachDetach > {
  static const char* value()
  {
    return "propio/AttachDetach";
  }

  static const char* value(const ::propio::AttachDetach&) { return value(); }
};


// service_traits::MD5Sum< ::propio::AttachDetachRequest> should match
// service_traits::MD5Sum< ::propio::AttachDetach >
template<>
struct MD5Sum< ::propio::AttachDetachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::propio::AttachDetach >::value();
  }
  static const char* value(const ::propio::AttachDetachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::propio::AttachDetachRequest> should match
// service_traits::DataType< ::propio::AttachDetach >
template<>
struct DataType< ::propio::AttachDetachRequest>
{
  static const char* value()
  {
    return DataType< ::propio::AttachDetach >::value();
  }
  static const char* value(const ::propio::AttachDetachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::propio::AttachDetachResponse> should match
// service_traits::MD5Sum< ::propio::AttachDetach >
template<>
struct MD5Sum< ::propio::AttachDetachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::propio::AttachDetach >::value();
  }
  static const char* value(const ::propio::AttachDetachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::propio::AttachDetachResponse> should match
// service_traits::DataType< ::propio::AttachDetach >
template<>
struct DataType< ::propio::AttachDetachResponse>
{
  static const char* value()
  {
    return DataType< ::propio::AttachDetach >::value();
  }
  static const char* value(const ::propio::AttachDetachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROPIO_MESSAGE_ATTACHDETACH_H
