// Generated by gencpp from file propio/AttachDetachResponse.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_ATTACHDETACHRESPONSE_H
#define PROPIO_MESSAGE_ATTACHDETACHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace propio
{
template <class ContainerAllocator>
struct AttachDetachResponse_
{
  typedef AttachDetachResponse_<ContainerAllocator> Type;

  AttachDetachResponse_()
    : success(false)
    , message()  {
    }
  AttachDetachResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::propio::AttachDetachResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::propio::AttachDetachResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AttachDetachResponse_

typedef ::propio::AttachDetachResponse_<std::allocator<void> > AttachDetachResponse;

typedef boost::shared_ptr< ::propio::AttachDetachResponse > AttachDetachResponsePtr;
typedef boost::shared_ptr< ::propio::AttachDetachResponse const> AttachDetachResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::propio::AttachDetachResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::propio::AttachDetachResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::propio::AttachDetachResponse_<ContainerAllocator1> & lhs, const ::propio::AttachDetachResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::propio::AttachDetachResponse_<ContainerAllocator1> & lhs, const ::propio::AttachDetachResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace propio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::propio::AttachDetachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::propio::AttachDetachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::AttachDetachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::AttachDetachResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::AttachDetachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::AttachDetachResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::propio::AttachDetachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::propio::AttachDetachResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::propio::AttachDetachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "propio/AttachDetachResponse";
  }

  static const char* value(const ::propio::AttachDetachResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::propio::AttachDetachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::propio::AttachDetachResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::propio::AttachDetachResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachDetachResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::propio::AttachDetachResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::propio::AttachDetachResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROPIO_MESSAGE_ATTACHDETACHRESPONSE_H
