// Generated by gencpp from file propio/ProcessImage.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_PROCESSIMAGE_H
#define PROPIO_MESSAGE_PROCESSIMAGE_H

#include <ros/service_traits.h>


#include <propio/ProcessImageRequest.h>
#include <propio/ProcessImageResponse.h>


namespace propio
{

struct ProcessImage
{

typedef ProcessImageRequest Request;
typedef ProcessImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessImage
} // namespace propio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::propio::ProcessImage > {
  static const char* value()
  {
    return "37b472b910195c5295b6dd8ac539437e";
  }

  static const char* value(const ::propio::ProcessImage&) { return value(); }
};

template<>
struct DataType< ::propio::ProcessImage > {
  static const char* value()
  {
    return "propio/ProcessImage";
  }

  static const char* value(const ::propio::ProcessImage&) { return value(); }
};


// service_traits::MD5Sum< ::propio::ProcessImageRequest> should match
// service_traits::MD5Sum< ::propio::ProcessImage >
template<>
struct MD5Sum< ::propio::ProcessImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::propio::ProcessImage >::value();
  }
  static const char* value(const ::propio::ProcessImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::propio::ProcessImageRequest> should match
// service_traits::DataType< ::propio::ProcessImage >
template<>
struct DataType< ::propio::ProcessImageRequest>
{
  static const char* value()
  {
    return DataType< ::propio::ProcessImage >::value();
  }
  static const char* value(const ::propio::ProcessImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::propio::ProcessImageResponse> should match
// service_traits::MD5Sum< ::propio::ProcessImage >
template<>
struct MD5Sum< ::propio::ProcessImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::propio::ProcessImage >::value();
  }
  static const char* value(const ::propio::ProcessImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::propio::ProcessImageResponse> should match
// service_traits::DataType< ::propio::ProcessImage >
template<>
struct DataType< ::propio::ProcessImageResponse>
{
  static const char* value()
  {
    return DataType< ::propio::ProcessImage >::value();
  }
  static const char* value(const ::propio::ProcessImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROPIO_MESSAGE_PROCESSIMAGE_H
