// Generated by gencpp from file propio/ProcessImageRequest.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_PROCESSIMAGEREQUEST_H
#define PROPIO_MESSAGE_PROCESSIMAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace propio
{
template <class ContainerAllocator>
struct ProcessImageRequest_
{
  typedef ProcessImageRequest_<ContainerAllocator> Type;

  ProcessImageRequest_()
    : isFront(false)  {
    }
  ProcessImageRequest_(const ContainerAllocator& _alloc)
    : isFront(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isFront_type;
  _isFront_type isFront;





  typedef boost::shared_ptr< ::propio::ProcessImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::propio::ProcessImageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessImageRequest_

typedef ::propio::ProcessImageRequest_<std::allocator<void> > ProcessImageRequest;

typedef boost::shared_ptr< ::propio::ProcessImageRequest > ProcessImageRequestPtr;
typedef boost::shared_ptr< ::propio::ProcessImageRequest const> ProcessImageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::propio::ProcessImageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::propio::ProcessImageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::propio::ProcessImageRequest_<ContainerAllocator1> & lhs, const ::propio::ProcessImageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.isFront == rhs.isFront;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::propio::ProcessImageRequest_<ContainerAllocator1> & lhs, const ::propio::ProcessImageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace propio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::propio::ProcessImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::propio::ProcessImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::ProcessImageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::ProcessImageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::ProcessImageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::ProcessImageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::propio::ProcessImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3629fc6e9ff898d8cea360736afbdb7";
  }

  static const char* value(const ::propio::ProcessImageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3629fc6e9ff898dULL;
  static const uint64_t static_value2 = 0x8cea360736afbdb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::propio::ProcessImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "propio/ProcessImageRequest";
  }

  static const char* value(const ::propio::ProcessImageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::propio::ProcessImageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ProcessImage.srv\n"
"bool isFront\n"
;
  }

  static const char* value(const ::propio::ProcessImageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::propio::ProcessImageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isFront);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessImageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::propio::ProcessImageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::propio::ProcessImageRequest_<ContainerAllocator>& v)
  {
    s << indent << "isFront: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isFront);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROPIO_MESSAGE_PROCESSIMAGEREQUEST_H
