// Generated by gencpp from file propio/StartStopExplorerResponse.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_STARTSTOPEXPLORERRESPONSE_H
#define PROPIO_MESSAGE_STARTSTOPEXPLORERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace propio
{
template <class ContainerAllocator>
struct StartStopExplorerResponse_
{
  typedef StartStopExplorerResponse_<ContainerAllocator> Type;

  StartStopExplorerResponse_()
    {
    }
  StartStopExplorerResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::propio::StartStopExplorerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::propio::StartStopExplorerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartStopExplorerResponse_

typedef ::propio::StartStopExplorerResponse_<std::allocator<void> > StartStopExplorerResponse;

typedef boost::shared_ptr< ::propio::StartStopExplorerResponse > StartStopExplorerResponsePtr;
typedef boost::shared_ptr< ::propio::StartStopExplorerResponse const> StartStopExplorerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::propio::StartStopExplorerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::propio::StartStopExplorerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace propio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::propio::StartStopExplorerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::StartStopExplorerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::StartStopExplorerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::propio::StartStopExplorerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "propio/StartStopExplorerResponse";
  }

  static const char* value(const ::propio::StartStopExplorerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::propio::StartStopExplorerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartStopExplorerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::propio::StartStopExplorerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::propio::StartStopExplorerResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PROPIO_MESSAGE_STARTSTOPEXPLORERRESPONSE_H
