// Generated by gencpp from file propio/StartPickAndPlace.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_STARTPICKANDPLACE_H
#define PROPIO_MESSAGE_STARTPICKANDPLACE_H

#include <ros/service_traits.h>


#include <propio/StartPickAndPlaceRequest.h>
#include <propio/StartPickAndPlaceResponse.h>


namespace propio
{

struct StartPickAndPlace
{

typedef StartPickAndPlaceRequest Request;
typedef StartPickAndPlaceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartPickAndPlace
} // namespace propio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::propio::StartPickAndPlace > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::propio::StartPickAndPlace&) { return value(); }
};

template<>
struct DataType< ::propio::StartPickAndPlace > {
  static const char* value()
  {
    return "propio/StartPickAndPlace";
  }

  static const char* value(const ::propio::StartPickAndPlace&) { return value(); }
};


// service_traits::MD5Sum< ::propio::StartPickAndPlaceRequest> should match
// service_traits::MD5Sum< ::propio::StartPickAndPlace >
template<>
struct MD5Sum< ::propio::StartPickAndPlaceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::propio::StartPickAndPlace >::value();
  }
  static const char* value(const ::propio::StartPickAndPlaceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::propio::StartPickAndPlaceRequest> should match
// service_traits::DataType< ::propio::StartPickAndPlace >
template<>
struct DataType< ::propio::StartPickAndPlaceRequest>
{
  static const char* value()
  {
    return DataType< ::propio::StartPickAndPlace >::value();
  }
  static const char* value(const ::propio::StartPickAndPlaceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::propio::StartPickAndPlaceResponse> should match
// service_traits::MD5Sum< ::propio::StartPickAndPlace >
template<>
struct MD5Sum< ::propio::StartPickAndPlaceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::propio::StartPickAndPlace >::value();
  }
  static const char* value(const ::propio::StartPickAndPlaceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::propio::StartPickAndPlaceResponse> should match
// service_traits::DataType< ::propio::StartPickAndPlace >
template<>
struct DataType< ::propio::StartPickAndPlaceResponse>
{
  static const char* value()
  {
    return DataType< ::propio::StartPickAndPlace >::value();
  }
  static const char* value(const ::propio::StartPickAndPlaceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROPIO_MESSAGE_STARTPICKANDPLACE_H
