// Generated by gencpp from file propio/StartPickAndPlaceRequest.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_STARTPICKANDPLACEREQUEST_H
#define PROPIO_MESSAGE_STARTPICKANDPLACEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace propio
{
template <class ContainerAllocator>
struct StartPickAndPlaceRequest_
{
  typedef StartPickAndPlaceRequest_<ContainerAllocator> Type;

  StartPickAndPlaceRequest_()
    {
    }
  StartPickAndPlaceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartPickAndPlaceRequest_

typedef ::propio::StartPickAndPlaceRequest_<std::allocator<void> > StartPickAndPlaceRequest;

typedef boost::shared_ptr< ::propio::StartPickAndPlaceRequest > StartPickAndPlaceRequestPtr;
typedef boost::shared_ptr< ::propio::StartPickAndPlaceRequest const> StartPickAndPlaceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::propio::StartPickAndPlaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace propio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::propio::StartPickAndPlaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "propio/StartPickAndPlaceRequest";
  }

  static const char* value(const ::propio::StartPickAndPlaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StartPickAndPlace.srv\n"
;
  }

  static const char* value(const ::propio::StartPickAndPlaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartPickAndPlaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::propio::StartPickAndPlaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::propio::StartPickAndPlaceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PROPIO_MESSAGE_STARTPICKANDPLACEREQUEST_H
