// Generated by gencpp from file propio/StartStopExplorerRequest.msg
// DO NOT EDIT!


#ifndef PROPIO_MESSAGE_STARTSTOPEXPLORERREQUEST_H
#define PROPIO_MESSAGE_STARTSTOPEXPLORERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace propio
{
template <class ContainerAllocator>
struct StartStopExplorerRequest_
{
  typedef StartStopExplorerRequest_<ContainerAllocator> Type;

  StartStopExplorerRequest_()
    : start(false)  {
    }
  StartStopExplorerRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::propio::StartStopExplorerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::propio::StartStopExplorerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartStopExplorerRequest_

typedef ::propio::StartStopExplorerRequest_<std::allocator<void> > StartStopExplorerRequest;

typedef boost::shared_ptr< ::propio::StartStopExplorerRequest > StartStopExplorerRequestPtr;
typedef boost::shared_ptr< ::propio::StartStopExplorerRequest const> StartStopExplorerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::propio::StartStopExplorerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::propio::StartStopExplorerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::propio::StartStopExplorerRequest_<ContainerAllocator1> & lhs, const ::propio::StartStopExplorerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::propio::StartStopExplorerRequest_<ContainerAllocator1> & lhs, const ::propio::StartStopExplorerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace propio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::propio::StartStopExplorerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::propio::StartStopExplorerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::propio::StartStopExplorerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::propio::StartStopExplorerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "propio/StartStopExplorerRequest";
  }

  static const char* value(const ::propio::StartStopExplorerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StartStopExplorer.srv\n"
"bool start\n"
;
  }

  static const char* value(const ::propio::StartStopExplorerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartStopExplorerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::propio::StartStopExplorerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::propio::StartStopExplorerRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROPIO_MESSAGE_STARTSTOPEXPLORERREQUEST_H
