// Generated by gencpp from file boeing_gazebo_model_attachment_plugin/Attach.msg
// DO NOT EDIT!


#ifndef BOEING_GAZEBO_MODEL_ATTACHMENT_PLUGIN_MESSAGE_ATTACH_H
#define BOEING_GAZEBO_MODEL_ATTACHMENT_PLUGIN_MESSAGE_ATTACH_H

#include <ros/service_traits.h>


#include <boeing_gazebo_model_attachment_plugin/AttachRequest.h>
#include <boeing_gazebo_model_attachment_plugin/AttachResponse.h>


namespace boeing_gazebo_model_attachment_plugin
{

struct Attach
{

typedef AttachRequest Request;
typedef AttachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Attach
} // namespace boeing_gazebo_model_attachment_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::boeing_gazebo_model_attachment_plugin::Attach > {
  static const char* value()
  {
    return "2586cf82c17da3ea82111514d10d4265";
  }

  static const char* value(const ::boeing_gazebo_model_attachment_plugin::Attach&) { return value(); }
};

template<>
struct DataType< ::boeing_gazebo_model_attachment_plugin::Attach > {
  static const char* value()
  {
    return "boeing_gazebo_model_attachment_plugin/Attach";
  }

  static const char* value(const ::boeing_gazebo_model_attachment_plugin::Attach&) { return value(); }
};


// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::AttachRequest> should match
// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::Attach >
template<>
struct MD5Sum< ::boeing_gazebo_model_attachment_plugin::AttachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::boeing_gazebo_model_attachment_plugin::Attach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::AttachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::AttachRequest> should match
// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::Attach >
template<>
struct DataType< ::boeing_gazebo_model_attachment_plugin::AttachRequest>
{
  static const char* value()
  {
    return DataType< ::boeing_gazebo_model_attachment_plugin::Attach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::AttachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::AttachResponse> should match
// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::Attach >
template<>
struct MD5Sum< ::boeing_gazebo_model_attachment_plugin::AttachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::boeing_gazebo_model_attachment_plugin::Attach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::AttachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::AttachResponse> should match
// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::Attach >
template<>
struct DataType< ::boeing_gazebo_model_attachment_plugin::AttachResponse>
{
  static const char* value()
  {
    return DataType< ::boeing_gazebo_model_attachment_plugin::Attach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::AttachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOEING_GAZEBO_MODEL_ATTACHMENT_PLUGIN_MESSAGE_ATTACH_H
