// Generated by gencpp from file boeing_gazebo_model_attachment_plugin/Detach.msg
// DO NOT EDIT!


#ifndef BOEING_GAZEBO_MODEL_ATTACHMENT_PLUGIN_MESSAGE_DETACH_H
#define BOEING_GAZEBO_MODEL_ATTACHMENT_PLUGIN_MESSAGE_DETACH_H

#include <ros/service_traits.h>


#include <boeing_gazebo_model_attachment_plugin/DetachRequest.h>
#include <boeing_gazebo_model_attachment_plugin/DetachResponse.h>


namespace boeing_gazebo_model_attachment_plugin
{

struct Detach
{

typedef DetachRequest Request;
typedef DetachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detach
} // namespace boeing_gazebo_model_attachment_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::boeing_gazebo_model_attachment_plugin::Detach > {
  static const char* value()
  {
    return "0a07b99010eab99684bb37117a445b93";
  }

  static const char* value(const ::boeing_gazebo_model_attachment_plugin::Detach&) { return value(); }
};

template<>
struct DataType< ::boeing_gazebo_model_attachment_plugin::Detach > {
  static const char* value()
  {
    return "boeing_gazebo_model_attachment_plugin/Detach";
  }

  static const char* value(const ::boeing_gazebo_model_attachment_plugin::Detach&) { return value(); }
};


// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::DetachRequest> should match
// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::Detach >
template<>
struct MD5Sum< ::boeing_gazebo_model_attachment_plugin::DetachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::boeing_gazebo_model_attachment_plugin::Detach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::DetachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::DetachRequest> should match
// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::Detach >
template<>
struct DataType< ::boeing_gazebo_model_attachment_plugin::DetachRequest>
{
  static const char* value()
  {
    return DataType< ::boeing_gazebo_model_attachment_plugin::Detach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::DetachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::DetachResponse> should match
// service_traits::MD5Sum< ::boeing_gazebo_model_attachment_plugin::Detach >
template<>
struct MD5Sum< ::boeing_gazebo_model_attachment_plugin::DetachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::boeing_gazebo_model_attachment_plugin::Detach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::DetachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::DetachResponse> should match
// service_traits::DataType< ::boeing_gazebo_model_attachment_plugin::Detach >
template<>
struct DataType< ::boeing_gazebo_model_attachment_plugin::DetachResponse>
{
  static const char* value()
  {
    return DataType< ::boeing_gazebo_model_attachment_plugin::Detach >::value();
  }
  static const char* value(const ::boeing_gazebo_model_attachment_plugin::DetachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOEING_GAZEBO_MODEL_ATTACHMENT_PLUGIN_MESSAGE_DETACH_H
