(cl:defpackage propio-srv
  (:use )
  (:export
   "ATTACHDETACH"
   "<ATTACHDETACH-REQUEST>"
   "ATTACHDETACH-REQUEST"
   "<ATTACHDETACH-RESPONSE>"
   "ATTACHDETACH-RESPONSE"
   "PROCESSIMAGE"
   "<PROCESSIMAGE-REQUEST>"
   "PROCESSIMAGE-REQUEST"
   "<PROCESSIMAGE-RESPONSE>"
   "PROCESSIMAGE-RESPONSE"
   "STARTPICKANDPLACE"
   "<STARTPICKANDPLACE-REQUEST>"
   "STARTPICKANDPLACE-REQUEST"
   "<STARTPICKANDPLACE-RESPONSE>"
   "STARTPICKANDPLACE-RESPONSE"
   "STARTSTOPEXPLORER"
   "<STARTSTOPEXPLORER-REQUEST>"
   "STARTSTOPEXPLORER-REQUEST"
   "<STARTSTOPEXPLORER-RESPONSE>"
   "STARTSTOPEXPLORER-RESPONSE"
  ))

