local_costmap:
  global_frame: robot_odom
  robot_base_frame: robot_base_link
  update_frequency: 3.0
  publish_frequency: 1.0
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  transform_tolerance: 0.5
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer: 
    observation_sources: laser_scan
    laser_scan: {
      sensor_frame: camera_front_link,
      data_type: LaserScan,
      topic: /scan,
      marking: true,
      clearing: true
    }

  inflation_layer:
    inflation_radius: 0.44
